### ISSUE TITLE
[BUG] Periodic null pointer exceptions sailing around the coast of a new island

### ISSUE THREAD

**Issue by ShammyLevva** [valheimPlus/ValheimPlus#416]
- **OS:** Windows 10
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5.5

**Describe the bug**

Console log showing the following 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <42f307805d854e54b796a9e21f117bfb>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
DungeonGenerator:PlaceRoom(RoomData, Vector3, Quaternion, RoomConnection, SpawnMode)
DungeonGenerator:PlaceRoom(RoomConnection, RoomData, SpawnMode)
DungeonGenerator:PlaceOneRoom(SpawnMode)
DungeonGenerator:PlaceRooms(SpawnMode)
DungeonGenerator:GenerateDungeon(SpawnMode)
DungeonGenerator:GenerateRooms(SpawnMode)
DungeonGenerator:Generate(Int32, SpawnMode)
DungeonGenerator:Generate(SpawnMode)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

Sometimes it was giving:

[Info   : Unity Log] 03/21/2021 14:07:16: Disabling OnboardTrigger  character_trigger

[Info   : Unity Log] 03/21/2021 14:07:16: Disabling FloatCollider  Ignore Raycast

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <42f307805d854e54b796a9e21f117bfb>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject)
Player:SetupPlacementGhost()
Player:UpdateAvailablePiecesList()
Player:OnInventoryChanged()
Inventory:Changed()
Inventory:RemoveItem(String, Int32)
Player:ConsumeResources(Requirement[], Int32)
Player:DMD<Player::UpdatePlacement>(Player, Boolean, Single)
Player:DMD<Player::Update>(Player)

**To Reproduce**

I was just sailing around the map unlocking new areas. It wasn't entirely consistent. However it looks like it's the generation of new dungeons that's causing issue.

**Expected behavior**

No NPEs

**Troubleshooting**

Report the bug - restart game

**Comment by greenskye** [comment]
I'm also having this issue.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <42f307805d854e54b796a9e21f117bfb>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

Started new world with only V+ installed and get this error.  Not sure if it's actually causing any problems or not, haven't had a chance to play enough on this world

**Comment by nxPublic** [comment]
Has anyone had any gameplay influence from these errors ? Would give us a start point to look for the issue.

**Comment by healiha** [comment]
@nxPublic It should be fixed by one of the PRs your merged today.

**Comment by ShammyLevva** [comment]
@nxPublic for me it was happening as I sailed around the coast and areas of map opened up. So it felt like it was during the code that would spawn dungeons. Does that help?

**Comment by turbo-david** [comment]
I'm seeing the same errors below. In our case we sailed south from our main base and landed. Setup a workbench/portal. We left a small boat/large boat there. Next time we went through the portal it would crash the game. We were able to make it back and deconstruct the boats/portal/workbench but entering the general area from another location will cause the crash.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
valheim_1  | Stack trace:
valheim_1  | ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <42f307805d854e54b796a9e21f117bfb>:0)
valheim_1  | (wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
valheim_1  | UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
valheim_1  | ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
valheim_1  | ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
valheim_1  | ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
valheim_1  | ZoneSystem:CreateGhostZones(Vector3)
valheim_1  | ZoneSystem:Update()
valheim_1  | NullReferenceException: Object reference not set to an instance of an object
valheim_1  |   at ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) [0x00029] in <42f307805d854e54b796a9e21f117bfb>:0
valheim_1  |   at (wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
valheim_1  | UnityEngine.Object:Internal_InstantiateSingle_Injected(Object, Vector3&, Quaternion&)
valheim_1  | UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
valheim_1  | UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
valheim_1  | UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
valheim_1  | ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
valheim_1  | ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
valheim_1  | ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
valheim_1  | ZoneSystem:CreateGhostZones(Vector3)
valheim_1  | ZoneSystem:Update()
valheim_1  | [Info   : Unity Log] 03/21/2021 01:47:19: Placed locations in zone -36,-52  duration 45.313 ms
valheim_1  | 03/21/2021 01:47:19: Placed locations in zone -36,-52  duration 45.313 ms
valheim_1  | [Info   : Unity Log] 03/21/2021 01:47:19: Placed locations in zone -35,-52  duration 0.304 ms
valheim_1  | 03/21/2021 01:47:19: Placed locations in zone -35,-52  duration 0.304 ms
valheim_1  | [Info   : Unity Log] 03/21/2021 01:47:19: Placed locations in zone -34,-52  duration 0.678 ms
valheim_1  | 03/21/2021 01:47:19: Placed locations in zone -34,-52  duration 0.678 ms
valheim_1  | 03/21/2021 01:49:36: Saved 51299 map points to disk.
valheim_1  | [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
valheim_1  | Stack trace:
valheim_1  | ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <42f307805d854e54b796a9e21f117bfb>:0)
valheim_1  | (wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
valheim_1  | UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
valheim_1  | ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
valheim_1  | ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
valheim_1  | ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
valheim_1  | ZoneSystem:CreateGhostZones(Vector3)
valheim_1  | ZoneSystem:Update()
valheim_1  | NullReferenceException: Object reference not set to an instance of an object
valheim_1  |   at ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) [0x00029] in <42f307805d854e54b796a9e21f117bfb>:0
valheim_1  |   at (wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
valheim_1  | UnityEngine.Object:Internal_InstantiateSingle_Injected(Object, Vector3&, Quaternion&)
valheim_1  | UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
valheim_1  | UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
valheim_1  | UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
valheim_1  | ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
valheim_1  | ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
valheim_1  | ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
valheim_1  | ZoneSystem:CreateGhostZones(Vector3)
valheim_1  | ZoneSystem:Update()

**Comment by ShammyLevva** [comment]
Quote "entering the general area from another location will cause the crash." did the game actually crash @turbo-david or did it just throw the error text in the console log and continue? 

In my case it threw the error but continued as normal.

**Comment by greenskye** [comment]
Still getting this error in 9.6. Still can't determine an actual effect. Config attached.

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <4e7137681808493383c9134cfb741930>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
DungeonGenerator:PlaceRoom(RoomData, Vector3, Quaternion, RoomConnection, SpawnMode)
DungeonGenerator:PlaceRoom(RoomConnection, RoomData, SpawnMode)
DungeonGenerator:PlaceOneRoom(SpawnMode)
DungeonGenerator:PlaceRooms(SpawnMode)
DungeonGenerator:GenerateDungeon(SpawnMode)
DungeonGenerator:GenerateRooms(SpawnMode)
DungeonGenerator:Generate(Int32, SpawnMode)
DungeonGenerator:Generate(SpawnMode)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <4e7137681808493383c9134cfb741930>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
DungeonGenerator:PlaceRoom(RoomData, Vector3, Quaternion, RoomConnection, SpawnMode)
DungeonGenerator:PlaceRoom(RoomConnection, RoomData, SpawnMode)
DungeonGenerator:PlaceOneRoom(SpawnMode)
DungeonGenerator:PlaceRooms(SpawnMode)
DungeonGenerator:GenerateDungeon(SpawnMode)
DungeonGenerator:GenerateRooms(SpawnMode)
DungeonGenerator:Generate(Int32, SpawnMode)
DungeonGenerator:Generate(SpawnMode)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <4e7137681808493383c9134cfb741930>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
DungeonGenerator:PlaceRoom(RoomData, Vector3, Quaternion, RoomConnection, SpawnMode)
DungeonGenerator:PlaceRoom(RoomConnection, RoomData, SpawnMode)
DungeonGenerator:PlaceOneRoom(SpawnMode)
DungeonGenerator:PlaceRooms(SpawnMode)
DungeonGenerator:GenerateDungeon(SpawnMode)
DungeonGenerator:GenerateRooms(SpawnMode)
DungeonGenerator:Generate(Int32, SpawnMode)
DungeonGenerator:Generate(SpawnMode)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimPlus.Container_Awake_Patch.Postfix (Container __instance, Inventory& ___m_inventory) (at <4e7137681808493383c9134cfb741930>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
DungeonGenerator:PlaceRoom(RoomData, Vector3, Quaternion, RoomConnection, SpawnMode)
DungeonGenerator:PlaceRoom(RoomConnection, RoomData, SpawnMode)
DungeonGenerator:PlaceOneRoom(SpawnMode)
DungeonGenerator:PlaceRooms(SpawnMode)
DungeonGenerator:GenerateDungeon(SpawnMode)
DungeonGenerator:GenerateRooms(SpawnMode)
DungeonGenerator:Generate(Int32, SpawnMode)
DungeonGenerator:Generate(SpawnMode)
ZoneSystem:SpawnLocation(ZoneLocation, Int32, Vector3, Quaternion, SpawnMode, List`1)
ZoneSystem:PlaceLocations(Vector2i, Vector3, Transform, Heightmap, List`1, SpawnMode, List`1)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()`


[valheim_plus.txt](https://github.com/valheimPlus/ValheimPlus/files/6190817/valheim_plus.txt)

**Comment by healiha** [comment]
I'm not able to reproduce this. Tried sailing around/near the coast, moving through portals but it doesn't happen. 😞

**Comment by turbo-david** [comment]
Mine crashed I haven't tested on 9.6 i can do that today and see if it occurs in the same spot

**Comment by healiha** [comment]
@turbo-david it would awesome if you could send me through discord a link to download your world (db + fwl files) and tell me where it happens so I can debug this!

**Comment by turbo-david** [comment]
Here is the issue. I tried it via single player and it wasn't doing it ..... I can send you the files later once I test it on 9.5.6

**Comment by turbo-david** [comment]
Ok so I just loaded in and wasn't able to get it to crash in that same area now..... soooooo not sure what is up.

**Comment by LordValerius** [comment]
I am getting the same errors also...Mainly when sailing near the coast of the Black Forest and the Plains.  Seems to occur when locations are being placed...which contain chests, if I had to guess.  I tested running V+ as the only mod (w/Inventory=true) and these errors occur.  I then changed the Inventory to =false and the errors seemed to have stopped.

**Comment by greenskye** [comment]
One thing I have noticed is that chests found in the world have original game sizes rather than what is specified in [Inventory]. Maybe this is causing the error message?

**Comment by healiha** [comment]
It has been addressed by #463 and shouldn't be happening again starting next release :)
